version: "3.9"
services:
    web:
        build: 
            context: .
            dockerfile: IntelliasVideoService/Dockerfile
        ports:
            - "8080:80"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"